version: '3.8'

services:
  client:
    build:
      context: ./flash-resume-client
      target: development
    container_name: flash-resume-client-dev
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    volumes:
      - ./flash-resume-client:/usr/src/app
      - exclude:/flash-resume-client/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    restart: always
  api:
    build:
      context: ./flash-resume-server
      target: development
    container_name: flash-resume-server-dev
    ports:
      - '${PORT}:3001'
      - '${DEBUG}:9229'
    command: sh -c "npx prisma migrate dev --name init && npm run dev"
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
    volumes:
      - ./flash-resume-server:/usr/src/app
      - exclude:/flash-resume-server/node_modules
    links:
      - postgres
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    restart: always
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
  exclude:
