version: "3.8"

services:
  client:
    build:
      context: ./react-template
      target: development
    container_name: react-develop
    ports:
      - '3000:8080'
    stdin_open: true
    tty: true
  api:
    build:
      context: ./typescript-node-template-v1
      target: development
    ports:
      - '${PORT}:3001'
      - '${DEBUG}:9229'
    command: sh -c "npx prisma migrate dev --name init && npm run dev"
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: development
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
